### ISSUE TITLE
Issue with compiling library

### ISSUE THREAD

**Issue by justinzelinsky** [ptaoussanis/carmine#125]
Hi,

I apologize if this is a trivial mistake on my part as I'm new to clojure but when I try to run my code, I get a compilation error

Exception in thread "main" java.lang.RuntimeException: No such var: encore/slurp-resource, compiling:(taoensso/carmine/commands.clj:148:7)

My code is based on the Luminus web framework tutorial. 

If you need any more specifics, I will be happy to provide them. Also, if this isn't the appropriate forum for this, please let me know.

Thank you!

**Comment by ptaoussanis** [comment]
Hi Justin, no apologies necessary - this is the right place to ask :-)

> Exception in thread "main" java.lang.RuntimeException: No such var: encore/slurp-resource, compiling:(taoensso/carmine/commands.clj:148:7)

It sounds like you've got a Leiningen dependency conflict. You can check by calling `lein deps :tree` at the command line.

Try adding a `[com.taoensso/encore "1.20.0"]` entry to your project.clj `:dependencies` **above** any other lib from me (the `com.taoensso` stuff).

Let me know if that helps? Happy Clojure-ing, cheers! :-)

**Comment by justinzelinsky** [comment]
Thanks for the quick response! That was the problem! Thanks also for the tips regarding dependency conflicts.

I'm loving what I'm seeing so far! Thank you very much!
