### ISSUE TITLE
how to use the cluster with carmine?

### ISSUE THREAD

**Issue by dlnufox** [ptaoussanis/carmine#134]
With carmine, I don't know how to use the cluster of redis.
How to connect to the cluster?
How much features of redis 3.0+ are being covered by carmine?

**Comment by ptaoussanis** [comment]
Hi xiaochaihu,

Carmine doesn't have Cluster support yet. This isn't something I have time to implement myself recently, PRs welcome: https://github.com/ptaoussanis/carmine/issues/76 for more info.

**Comment by dlnufox** [comment]
Thanks.
