### ISSUE TITLE
Dependency problem when used simultaneously with Apache Storm

### ISSUE THREAD

**Issue by siphiuel** [ptaoussanis/carmine#142]
Hi,

it seems that there is a dependency conflict when using both Apache Storm and Carmine in a single Leiningen project. 

Having both dependencies defined as:

```
[org.apache.storm/storm-core "0.9.5"]
[com.taoensso/carmine "2.11.1"]]
```

yields `namespace 'taoensso.carmine' not found` errors that can be fixed by adding `:exclusions [commons-codec]` to Storm library import.

Details can be found in this [StackOverflow post](http://stackoverflow.com/questions/32519992/properly-importing-apache-storm-dependencies-in-clojure/32525721#32525721). 

Thanks,
Vitaliy.

**Comment by ptaoussanis** [comment]
Hi Vitaliy,

Yes, this looks like a dependency conflict. You can resolve in one of three ways:
1. Place Carmine's dep entry before Storm
2. Use `:exclusions` as you've dove
3. Add your own dep entry for commons-codec before Storm

Any of these 3 will make sure that the newer commons-codec is pulled in. Does that help?

**Comment by siphiuel** [comment]
Hi Peter,

yes, that definitely helps. Thanks!

I am closing the issue.
