### ISSUE TITLE
Is carmine support Redis notification ?

### ISSUE THREAD

**Issue by jeremieca** [ptaoussanis/carmine#154]
Hello,

Is carmine driver support Redis notification (since redis 2.8.0) ?
Notifications documentation available here : http://redis.io/topics/notifications

Thanks,
Jeremie C.

**Comment by ptaoussanis** [comment]
Hi Jeremie,

From the linked doc:
```
Events are delivered using the normal Pub/Sub layer of Redis, so clients implementing Pub/Sub are able to use this feature without modifications.
```

So I believe the answer is _yes_ because I don't think Carmine actually needs to do anything special to support notifications. Haven't used them myself, but looks like they just operate over the normal pub/sub API.

Hope that helps / makes sense?

Cheers :-)

**Comment by jeremieca** [comment]
Thanks. :)

**Comment by ptaoussanis** [comment]
No problem - good luck with Clojure + Redis, they're a great fit together! :-)
