### ISSUE TITLE
[Error] No such var: encore/read-edn

### ISSUE THREAD

**Issue by prateekbhatt** [ptaoussanis/carmine#158]
I have tried both versions 2.12.2 and 2.12.1, and get the same error:

```
:cause No such var: encore/read-edn
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.RuntimeException: No such var: encore/read-edn, compiling:(taoensso/nippy/utils.clj:36:43)
   :at [clojure.lang.Compiler analyze Compiler.java 6543]}
  {:type java.lang.RuntimeException
   :message No such var: encore/read-edn
   :at [clojure.lang.Util runtimeException Util.java 221]}]
```

**Comment by ptaoussanis** [comment]
Hi Prateek, please check for dependency conflicts with `lein deps :tree`, and run `lein clean` between attempts to make sure you don't have any bad build artefacts.

**Comment by prateekbhatt** [comment]
Thanks, you are right, I was using the 'tower' library which uses an older version on encore. Fixed the issue.

**Comment by ptaoussanis** [comment]
No problem, best of luck! :-)
