### ISSUE TITLE
Inspecting the items on a worker queue  

### ISSUE THREAD

**Issue by jdkealy** [ptaoussanis/carmine#160]
Hi, 

I was wondering if you had a way to inspect the items on a worker queue. If not I was wondering if you could explain a little about what redis types are being used behind the scenes. 

e.g. I'd like to provide a GUI like sidekiq to show the user "X number of jobs enqueued", etc. Is there a way to do this ?

**Comment by ptaoussanis** [comment]
Hi John,

There's a couple utils - incl. `message-status` and `queue-status`. Please see the [API docs](http://ptaoussanis.github.io/carmine/taoensso.carmine.message-queue.html) for more info.
