### ISSUE TITLE
Pluggable serialization methods 

### ISSUE THREAD

**Issue by robert-zaremba** [ptaoussanis/carmine#162]
Would be great to have an option to change the serialization mechanism (eg [MessagePack](http://msgpack.org/index.html)) instead of sticking to Nippy.

**Comment by ptaoussanis** [comment]
Hi Robert, would be open to this + should be an easy mod.

Am curious what the motivation is in your case?

**Comment by robert-zaremba** [comment]
Great.
I have other application (written in Go) which serializes complex structures using MessagePack. I would like to this data from Clojure.

**Comment by ptaoussanis** [comment]
In hindsight, actually closing this for now. If folks would like to user other serialization formats, that's simple enough by just reading the key as a string and using whatever method you'd prefer.

Adding all the machinery to try do this automatically while still keeping it flexible would bring a lot of complexity for very little value.

Even the current auto serialization is a little dubious. Overall think it's worth the extra convenience, but only barely. In most cases I'd recommend making serialization (with any format) explicit in the same way.
