### ISSUE TITLE
Publishing a Keyword results in a String being received

### ISSUE THREAD

**Issue by expez** [ptaoussanis/carmine#167]
I'm on redis 3.0.6 and on carmine version 2.12.2.

```clj
(def listener (car/with-new-pubsub-listener redis
                {"*" println}
                (car/psubscribe "*")))

;;=> [psubscribe * 1]
;;=> #<Var@1344891d: {...}>

(car/publish redis "chn" :keyword)
;;=> [pmessage * chn keyword]
;;=> 1

(car/wcar redis (car/publish "chn" {:keyword 1}))
;;=> [pmessage * chn {:keyword 1}]
;;=> 1
```

Is this a bug, or do keywords only work when they're part of some data structure like the map above?

**Comment by ptaoussanis** [comment]
Hi there, please see https://github.com/ptaoussanis/carmine#serialization

**Comment by expez** [comment]
Thanks.  I misread the docs to mean that keywords were (de)serialized transparently for v 2+.

**Comment by ptaoussanis** [comment]
No problem, good luck!
