### ISSUE TITLE
carmine.locks/acquire-lock: remove lua scripts?

### ISSUE THREAD

**Issue by R3D4C73D** [ptaoussanis/carmine#177]
The comment in the code mentions waiting for https://github.com/antirez/redis/issues/931 to be resolved.  Well, it's resolved now.  🙂  You can use `SET` with nx and ex all in one call as of Redis 2.6.12.

**Comment by ptaoussanis** [comment]
Hi there, updating this code isn't a major priority atm since it's working as it is (and supports folks with older Redis servers). Appreciate you checking though, cheers :-)
