### ISSUE TITLE
carmine.locks/release-lock: inline lua

### ISSUE THREAD

**Issue by R3D4C73D** [ptaoussanis/carmine#178]
I see that much of the inline lua scripts have been broken out into their own files at `src/lua`, which I completely support.  However, the lua in `carmine.locks/release-lock` was missed.  (Also, `carmine.locks/acquire-lock` was missed, but that would be taken care of by https://github.com/ptaoussanis/carmine/issues/177)

**Comment by ptaoussanis** [comment]
Hi there, moving the inline lua scripts to external files is not a priority atm - esp. for such short scripts.

Thanks for checking though, cheers! :-)
