### ISSUE TITLE
Unable to get timeout-ms to work when using wcar

### ISSUE THREAD

**Issue by murtaza52** [ptaoussanis/carmine#179]
Hi,

I am using wcar, and have added the timeout-ms to the spec, however still cant get the conn to timeout. Using a proxy have added a latency to redis. 

{:pool
 {:max-total-per-key 64,
  :max-idle-per-key 16,
  :min-idle-per-key 12,
  :max-wait-ms 5000,
  :soft-min-evictable-idle-time-ms 60000,
  :min-evictable-idle-time-ms -1},
 :spec {:host "localhost", :port 6380, :timeout-ms 500},
 :statsd-name "localhost",
 :slave {:host "localhost", :port 6380 :timeout-ms 500}}

**Comment by ptaoussanis** [comment]
Hi there, sorry for the delay replying. Please feel free to reopen with a reproducible example that I can look at if you'd still like me to debug - thanks!
