### ISSUE TITLE
API reference seems stuck in version 2.13.0

### ISSUE THREAD

**Issue by aranhoide** [ptaoussanis/carmine#186]
While the github README promotes 2.14.0 as the stable version, the API reference linked from there is titled "Carmine 2.13.0", and the installation instructions there have you installing 2.13.0.  Even if there have been no API changes since 2.13.0 (is this the case?), bumping the version number in the API reference would avoid confusion.

**Comment by ptaoussanis** [comment]
Updated, thanks!

**Comment by aranhoide** [comment]
Thanks for the quick reply!  I see you've upgraded all the way to 2.15.0-alpha2.  I was expecting the stable (2.14.0) version instead, but I imagine you mean this and I myself just use the doc shortcut in emacs, so I'll close this issue.

**Comment by ptaoussanis** [comment]
There's minor differences (if any) between these versions, and 2.15.0 is due for a release soon as I can find some time :-)
