### ISSUE TITLE
Add support for listing all subscribed channels

### ISSUE THREAD

**Issue by pupeno** [ptaoussanis/carmine#187]
http://stackoverflow.com/questions/8165188/redis-command-to-get-all-available-channels-for-pub-sub

**Comment by ptaoussanis** [comment]
Hi Pablo, sorry for the delay replying.

Just to clarify: you're asking about adding support for the `PUBSUB CHANNELS` command to Carmine? Should [already be available](https://github.com/ptaoussanis/carmine/blob/28d252cc104f00cdca27dd22ddf5874f244b7276/src/commands.edn#L65) from what I can tell?

Also keep in mind that you can always use `car/redis-call` to execute arbitrary Redis commands (for example, if they're added to Redis but haven't been made available in Carmine yet).

Does that help?
