### ISSUE TITLE
 how to use `redis-call`

### ISSUE THREAD

**Issue by xuwv** [ptaoussanis/carmine#189]
Hello,

I can't find any doc about `redis-call`, did I do something wrong?

`(require '[taoensso.carmine :as car :refer [wcar]])`
`=> nil`
`(wcar {} (car/redis-call [:get "key"]))`
`IllegalArgumentException Don't know how to create ISeq from: java.lang.Integer  clojure.lang.RT.seqFrom (RT.java:542)`

**Comment by ptaoussanis** [comment]
Hey there, thanks for pinging me about this! Was a bug introduced in v2.15.0. Have just pushed v2.15.1 which should correct the problem.

Cheers :-)

**Comment by xuwv** [comment]
Hello then, but still could not find artifact 2.15.1 in maven central or clojars?

**Comment by ptaoussanis** [comment]
Oh, excuse me! Something failed with the upload and didn't notice; should be [okay now](https://clojars.org/com.taoensso/carmine). Cheers :-)

**Comment by xuwv** [comment]
Thanks, cheers :-)
