### ISSUE TITLE
Does the connection close?

### ISSUE THREAD

**Issue by r-custodio** [ptaoussanis/carmine#202]
By this example  
```(defmacro wcar* [& body] `(car/wcar server1-conn ~@body))```

I would like to know if the connection close everytime? There is a state for the connection?

**Comment by kenan-rhoton** [comment]
I'm running into a problem I suspect is related to this: I'm running a project with clojure-expectations for the unit tests, and it seems like some process related to carmine never closes, which does not allow unit tests to finish (despite there being no errors and everything working perfectly).

I've sniffed around and it seems that this is do to some thread pool not being closed properly, but I wouldn't know how to forcefully close the connection after the tests are done...

**Comment by ptaoussanis** [comment]
Hi Rafael, Carmine uses a connection pool by default. Not sure what you mean by "state"? In any case, you can skip or override the default connection pool through options to `wcar`.

Hope that helps?

**Comment by ptaoussanis** [comment]
@kenan-rhoto Is this still an issue with `2.18.0`? If so, could you please create a new issue with a reproducible example? Thanks!

**Comment by kenan-rhoton** [comment]
We moved back to `clojure.test` as a workaround, as that forces a termination upon finishing the tests, so we haven't experienced this anymore. I can try to quickly reproduce it to see if it works, if no one else wants to.
