### ISSUE TITLE
2.17.0 does not allow to create war files

### ISSUE THREAD

**Issue by abhisek-ghosh** [ptaoussanis/carmine#205]
Hi,
I was trying to refer your repository in my code.  My code will need SSL connection. So I pulled 2.17.0 version but I found that when I am trying to create a war file of my project using (lein ring uberwar), the process is freezing. Although I am able to successfully create a war file of my project using 2.16.0. Also if you can provide an example of using the ssl connection configuration structure, I could not find the same in the readme

**Comment by ptaoussanis** [comment]
Thanks for the report, seem to be able to reproduce this- will look into it :+1:

**Comment by ptaoussanis** [comment]
Resolved with `2.18.0`, now on Clojars.

**Comment by abhisek-ghosh** [comment]
Thanks. I have tested 2.18.0 and it works both for SSL and non-SSL
