### ISSUE TITLE
Consider Datomic (esp. Cloud) integration

### ISSUE THREAD

**Issue by eoliphan** [ptaoussanis/carmine#212]
Datomic Cloud's tighter integration with AWS comes at the cost of some tradeoffs.  In particular, _bytes_ type isn't supported and the _string_ type is now limited to 4K.  Approaches such as the one described [here](https://vvvvalvalval.github.io/posts/2018-05-01-making-a-datomic-system-gdpr-compliant.html) outline possible integration scenarios.   Perhaps some of the Tundra stuff might be helpful.

**Comment by ptaoussanis** [comment]
Hi there!

I'm afraid I'd need some more details to understand what exactly you're proposing. You'd like Datomic Cloud as a possible storage target for Tundra? I'm not sure how that relates to the bytes or string type limitation (or the linked GDPR article).

Sorry, may be missing something obvious :-)

**Comment by ptaoussanis** [comment]
Closing for now, please feel to reopen if you'd like to follow up. Thanks!
