### ISSUE TITLE
Upgraded connection pool blocks program from exiting

### ISSUE THREAD

**Issue by tetigi** [ptaoussanis/carmine#213]
Hey there -

We're using Carmine 2.19.0, and it seems that the connection pools are blocking the Java process from exiting. I have created a minimal project demonstrating the problem here, along with a description of the behaviour: https://github.com/tetigi/carmine-issue

Have confirmed that the blocking happens on two different devices, on Java 8, 9 and 10. Downgrading Carmine to 2.18.2 or not creating a thread pool (`:pool :none`) fixes the problem.

Still trying to figure out what the exact problem with commons-pool2 is. Seems like it was introduced in this commit: https://github.com/ptaoussanis/carmine/commit/b850ebb6b610de995d0885efbc067bfc18f0bae8

**Comment by ptaoussanis** [comment]
Hi there, thanks for the report. Confirmed on my end.

Looks like an [upstream bug](https://issues.apache.org/jira/browse/POOL-348) from commons-pool. Since we don't actually need the newest version, will issue a hotfix shortly that reverts the version bump update.

**Comment by tetigi** [comment]
Thanks for the quick fix! Looks great now.
