### ISSUE TITLE
Mark v2.14.0 as breaking due to serialization changes?

### ISSUE THREAD

**Issue by timmc-bcov** [ptaoussanis/carmine#216]
Carmine v2.14.0 upgraded Nippy to v2.12.0, which writes data that older versions cannot read. We ran into this when trying to upgrade Carmine from 2.6.2 to 2.19.1—since we have both old and new servers running simultaneously in a green/blue deploy type situation, and both sets are both reading from and writing to the cache, this breaks the old servers.

Our workaround is to version the cache keys and allow the new servers to warm up their "side" of the cache, but I think it would make sense to mark Carmine v2.14.0 as breaking forwards compatibility for older versions reading newer data.

**Comment by ptaoussanis** [comment]
Hi there, thanks for the report (and apologies for the trouble!). Will update the CHANGELOG in a moment 👍
