### ISSUE TITLE
Connection pool documentation -- :none vs {}

### ISSUE THREAD

**Issue by crclark** [ptaoussanis/carmine#217]
The README states

> A simple example spec with no pool and one server using redistogo.com would be:
> `(def server1-conn {:pool {} :spec {:uri \"redis://redistogo:pass@panga.redistogo.com:9475/\"}})`

but [the docs for `wcar`](http://ptaoussanis.github.io/carmine/taoensso.carmine.html#var-wcar) say

> A `:none` pool can be used to skip connection pooling (not recommended).

From my reading of the code, it seems that the README is wrong and the `wcar` docs are correct. Passing `{}` for `:pool` seems to create a pool with default settings, right?

I was also confused as to how the pool would get reused if I'm just passing in a map of options, but I see that `conn-pool` is memoized. This might be worth mentioning in the docs for `wcar` or `conn-pool`.

**Comment by ptaoussanis** [comment]
README has a typo, will correct shortly- thanks for the report!
