### ISSUE TITLE
Having java.lang.Exception: namespace 'taoensso.carmine.commands' not found

### ISSUE THREAD

**Issue by coxchen** [ptaoussanis/carmine#222]
Hi,

I'm having java.lang.Exception: namespace 'taoensso.carmine.commands' not found with version 2.19.1 . Can anyone suggest how to fix this problem?

Thanks,
- Cox

**Comment by ptaoussanis** [comment]
Hi there! Please check for possible [dependency conflicts](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md), thanks!

**Comment by coxchen** [comment]
Fixed, thanks.
It turns out to be version conflict of tools.reader .
