### ISSUE TITLE
Task level lock-ms instead of a global lock period

### ISSUE THREAD

**Issue by fhalde** [ptaoussanis/carmine#223]
A message queue generally has varied types of task that come in. Some might take longer time while some can be instantaneous

Having a global level lock timeout doesn't let you to allow retries of certain tasks quicker

Having a task level lock-ms helps you with that

1. A task that we know takes long time can be given a sufficiently large lock timeout so as to avoid double work
2. A task that generally completes quickly can be given a small lock timeout so that it can be retried faster in case it has stalled

**Comment by ptaoussanis** [comment]
Hi there,

To clarify: this is a feature request to add optional task-level lock timeouts for Carmine's message queue? If so, PR welcome- thanks!

**Comment by ptaoussanis** [comment]
Closing, will be included in next v3 release as part of #278
