### ISSUE TITLE
Stale mids (message ids) in the :done key of queue

### ISSUE THREAD

**Issue by frankitox** [ptaoussanis/carmine#225]
Hello, maybe this is something someone already found while using workers.

The thing is, when I use queues sometimes I end up with stale mids (message ids) in the `:done` set of the queue. If I try to get the [message status](http://ptaoussanis.github.io/carmine/taoensso.carmine.message-queue.html#var-message-status) it returns `nil`. I suspect this happens when the worker processing the queue item crashes, but I'm not sure.

For now I have a little function to clean the stale mids.

```clojure
(defn clean-done [conn-opts & qnames]
  (when (seq qnames)
    (doseq [qname qnames]
      (let [{:keys [done]} (car-mq/queue-status server-connection qname)]
        (doseq [mid done]
          (when-not (car/wcar conn-opts (car-mq/message-status qname mid))
            (car/wcar conn-opts (car/srem (car/key :carmine :mq qname :done) mid))))))))
```

From the library design perspective, there's any case where it makes sense to keep a mid with nil status in the `:done` set of the queue?

**Comment by ptaoussanis** [comment]
Hi there!

Yes, it's possible for items to temporarily sit the `done` state until GC'd (until the item is next picked up again for processing). More info in the message-queue ns docstring, and [here](https://github.com/ptaoussanis/carmine/blob/master/message-states.jpg).

Hope that helps!
