### ISSUE TITLE
Github Doku a bit confusing

### ISSUE THREAD

**Issue by spiderbit** [ptaoussanis/carmine#226]
On the Project description you use that as example:
`
(def server1-conn {:pool {} :spec {:uri \"redis://redistogo:pass@panga.redistogo.com:9475/\"}})`

The escaping ( \ ) of the " seem to be wrong, at least it works here without them, I am not very experienced in Closure yet but that should be wrong.

like that:
`
(def server1-conn {:pool {} :spec {:uri "redis://redistogo:pass@panga.redistogo.com:9475/"}})`

**Comment by ptaoussanis** [comment]
Hi Stefan, fixing in latest release- thanks for mentioning this!
