### ISSUE TITLE
Make HSET variadic? Deprecate HMSET?

### ISSUE THREAD

**Issue by handerpeder** [ptaoussanis/carmine#232]
Starting with Redis 4.0 HSET is variadic. Is there a reason for not updating carmine/hset to support this?

Also from the Redis documentation:

> As per Redis 4.0.0, HMSET is considered deprecated. Please use HSET in new code.

**Comment by ptaoussanis** [comment]
Hi there!

Carmine's `hset` is variadic. In general, Carmine's commands inherit their definition directly from the Redis [command spec](https://raw.githubusercontent.com/antirez/redis-doc/master/commands.json) .

Likewise `hmset` will be marked as deprecated if/when it is marked as deprecated in Redis.

Hope that helps!
