### ISSUE TITLE
Setting large bitfields and ignoring return values?

### ISSUE THREAD

**Issue by theronic** [ptaoussanis/carmine#233]
When I try to set a billion bits on a bitfield, I get a "Java heap space" exception, but it works for fewer bits:
```
(wcar*
  (doseq [x (range 1e9)]
    (redis/bitfield "users:roles" "SET" "u1" x (mod x 2))
    (redis/bitfield "users:allowed?" "SET" "u1" x 1))
    (redis/bitcount "users:roles"))
```

How should I be committing these performantly and ignoring the intermediate write results? Do I need to batch them in separate calls to wcar? I know I can chain many bit ops in one call, but it's not clear what those limits are.

**Comment by ptaoussanis** [comment]
Hi there,

Everything in your `doseq` is being pipelined w/in a single `wcar*` call - and the results accumulated.
You'll need to force the pipeline to end before it gets too big- either by calling `wcar*` multiple times (e.g. 1000x `wcar*` each executing 1e6 calls), or by using the `with-replies` function.

Hope that helps!
