### ISSUE TITLE
Carmine connection time-out 

### ISSUE THREAD

**Issue by shahceg** [ptaoussanis/carmine#234]
Hi @ptaoussanis ,

I am new to redis. I am connecting redis AWS from carmine clojure library.
I was able to ping (car/ping) from my local machine to dev server , but the same code is throwing connection time out in Actual DEV Environment. Following is the error

:cause connect timed out
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Carmine connection error
   :data {}
   :at [taoensso.carmine.connections$pooled_conn invokeStatic connections.clj 218]}
  {:type java.net.SocketTimeoutException
   :message connect timed out
   :at [java.net.PlainSocketImpl socketConnect PlainSocketImpl.java -2]}]
 :trace
 [[java.net.PlainSocketImpl socketConnect PlainSocketImpl.java -2]
  [java.net.AbstractPlainSocketImpl doConnect AbstractPlainSocketImpl.java 350]
  [java.net.AbstractPlainSocketImpl connectToAddress AbstractPlainSocketImpl.java 206]
  [java.net.AbstractPlainSocketImpl connect AbstractPlainSocketImpl.java 188]
  [java.net.SocksSocketImpl connect SocksSocketImpl.java 392]
  [java.net.Socket connect Socket.java 589]
  [taoensso.carmine.connections$make_new_connection invokeStatic connections.clj 84]
  [taoensso.carmine.connections$make_new_connection invoke connections.clj 64]
  [taoensso.carmine.connections$make_connection_factory$reify__35228 makeObject connections.clj 123]
  [org.apache.commons.pool2.impl.GenericKeyedObjectPool create GenericKeyedObjectPool.java 1041]
  [org.apache.commons.pool2.impl.GenericKeyedObjectPool borrowObject GenericKeyedObjectPool.java 357]
  [org.apache.commons.pool2.impl.GenericKeyedObjectPool borrowObject GenericKeyedObjectPool.java 279]
  [taoensso.carmine.connections.ConnectionPool get_conn connections.clj 48]
  [taoensso.carmine.connections$pooled_conn invokeStatic connections.clj 213]
  [taoensso.carmine.connections$pooled_conn invoke connections.clj 207]
  [predictions_api.components.redis_cache$redis_connection_info invokeStatic redis_cache.clj 35]
  [predictions_api.components.redis_cache$redis_connection_info invoke redis_cache.clj 30]
  [predictions_api.config.component_system_map$predictions_api_system invokeStatic component_system_map.clj 31]
  [predictions_api.config.component_system_map$predictions_api_system invoke component_system_map.clj 20]
  [predictions_api.endpoints$init invokeStatic endpoints.clj 677]
  [predictions_api.endpoints$init invoke endpoints.clj 672]
  [clojure.lang.Var invoke Var.java 380]
  [ring.server.standalone$serve invokeStatic standalone.clj 95]
  [ring.server.standalone$serve doInvoke standalone.clj 75]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [ring.server.leiningen$serve invokeStatic leiningen.clj 13]
  [ring.server.leiningen$serve invoke leiningen.clj 10]
  [clojure.lang.Var invoke Var.java 384]
  [predictions_api.endpoints.main$_main invokeStatic main.clj 1]
  [predictions_api.endpoints.main$_main invoke main.clj 1]
  [clojure.lang.AFn applyToHelper AFn.java 152]
  [clojure.lang.AFn applyTo AFn.java 144]
  [predictions_api.endpoints.main main nil -1]]

My Connection info : {:pool {}, :spec {:uri \"redis://prediction-redis.chq3qq.ng.0001.use1.cache.amazonaws.com:6379\"}}
i tried with 
{:pool {}, :spec {:host \"prediction-redis.chq3qq.ng.0001.use1.cache.amazonaws.com\", :port 6379}} this also. 

But it's working from my local Mac machine. Can you guide ?

**Comment by ptaoussanis** [comment]
Hi there, is this question still relevant?

**Comment by shahceg** [comment]
Nope, thanks for asking. it can be closed !

**Comment by ptaoussanis** [comment]
Great, thanks for the confirmation. Apologies for the huge delay replying to your question!
