### ISSUE TITLE
Can't run tests locally

### ISSUE THREAD

**Issue by renatoalencar** [ptaoussanis/carmine#241]
I cloned the repo and I'm trying to run the tests, but they're failing when I try to run them together with `lein test` and with `./run-tests env`. They all pass when I run it individually, so I believe that's something related to a concurrency issue, but I can't simply figure it out.

I'm attaching the output of running `./run-tests` with an empty env file: [test-results.txt](https://github.com/ptaoussanis/carmine/files/5327468/test-results.txt)

The versions of what I'm using:

```
Leiningen 2.9.4 on Java 14-internal OpenJDK 64-Bit Server VM
redis  latest  84c5f6e03bf0 (Docker image)
```

**Comment by ptaoussanis** [comment]
Closing, will be addressed in forthcoming release.
