### ISSUE TITLE
Advertise TLS support in the README?

### ISSUE THREAD

**Issue by aranhoide** [ptaoussanis/carmine#243]
Apparently, Carmine has been supporting TLS for a while via `(-> conn-opts :spec :ssl-fn)`.  This is documented in the [wcar](http://ptaoussanis.github.io/carmine/taoensso.carmine.html#var-wcar) docstring, and it's not qualified as experimental anywhere in the source code, so I suppose it's a supported feature.  I have tested a custom `ssl-fn` (with client verification and pinned server cert) and it works well.

Adding a bullet point to the [Features](https://github.com/ptaoussanis/carmine#features) list advertising such support in the README would help users requiring this support, and perhaps increase Carmine adoption.

(I'm assuming that the "Pluggable compression and encryption support (v2+)" refers to encrypting/compressing data at rest in redis, not encrypting/compressing the transport.  If I'm wrong about this, I still suggest adding an explicit reference to SSL/TLS).

**Comment by ptaoussanis** [comment]
Hi @aranhoide, apologies for the long delay replying and for any confusion.
You are correct that SSL is indeed supported (not experimental, etc.).

The upcoming Carmine v4 will contain new documentation re: connection options, and I'll make sure to mention the SSL there.

Cheers!
