### ISSUE TITLE
Enqueue option to enqueue something with an init backoff

### ISSUE THREAD

**Issue by st3fan** [ptaoussanis/carmine#244]
In `message_queue.clj` there is the following comment in `enqueue`:

```
;; TODO Option to enqueue something with an init backoff?
```

This is a feature I could really use. Is this something I can help to contribute to this project? Would you accept a patch to implement this?

**Comment by st3fan** [comment]
I created an initial draft pull request at https://github.com/ptaoussanis/carmine/pull/245

**Comment by ptaoussanis** [comment]
https://github.com/ptaoussanis/carmine/releases/tag/v3.1.0 is now on Clojars 👍  
Thanks again.

Cheers!
