### ISSUE TITLE
auto fail over support

### ISSUE THREAD

**Issue by tolitius** [ptaoussanis/carmine#253]
first off, thank you for creating and maintaining this library!

I see #134 and #76 and also that spec [takes a single host](https://github.com/ptaoussanis/carmine/blob/master/src/taoensso/carmine/connections.clj#L220)

Looking to make sure a client can auto fail over when redis promotes a new host to master:
![image](https://user-images.githubusercontent.com/136575/128438610-878bd1c2-c243-4973-87f0-3419197923de.png)

[MasterReplica](https://lettuce.io/core/release/api/io/lettuce/core/masterreplica/MasterReplica.html) connector from `lettuce` takes a sequence of URIs that it internally iterates over to make sure "the next" available node is used:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/136575/128438134-68a24cf2-e402-443c-9928-fc289b1c6672.png">

I don't think carmine is there _yet_: i.e. would not support an auto fail over. But instead of assuming it, I'd like to confirm to make sure I did not miss anything.

**Comment by ptaoussanis** [comment]
@tolitius Hi Anatoly, apologies for the long delay.

You are correct: Carmine does not currently support any auto fail-over mechanism.
Please 👍 https://github.com/ptaoussanis/carmine/issues/272 if you're still interested in this capability.

**Comment by tolitius** [comment]
all good
thanks for getting back!
"👍 "ed the #272
