### ISSUE TITLE
Building up Redis tx-data without actually executing

### ISSUE THREAD

**Issue by theronic** [ptaoussanis/carmine#256]
I have some business logic that needs to build up a sequence of side effects, including some Redis commands. How can I use Carmine to build up the commands that will be executed in a pipeline without actually executing them?

Basically, a version of `wcar` that returns "tx-data", which can then be executed later.

**Comment by theronic** [comment]
Realized I can do this by moving my calls to Carmine into functions and mocking those functions.

**Comment by ptaoussanis** [comment]
@theronic Hi Petrus, thanks for updating the issue with your result. Apologies for the delayed reply, but happy you found a solution so long 👍
