### ISSUE TITLE
How to use MAXLEN with streams XADD?

### ISSUE THREAD

**Issue by glenthomas** [ptaoussanis/carmine#258]
Hello,

I am trying to use the `MAXLEN` option with `xadd` but can't figure out the correct syntax.

My xadd works:

```
(car/xadd stream-name "*" data-map)
```

Could somebody please provide a small code sample for adding MAXLEN, with ~ also, to this? Thanks.

**Comment by ptaoussanis** [comment]
Hi Glen!

Carmine's API is just a thin wrapper around the underlying Redis API. So just checking: have you seen the Redis documentation for this?

- [API docs](https://redis.io/commands/XADD)
- [Streams info](https://redis.io/topics/streams-intro)

Also any general Redis examples you find online should in principle be directly applicable to Carmine.

Hope that's at least some help in the meantime! Cheers :-)

**Comment by glenthomas** [comment]
Hello Peter,

Yes I have tried code like this, but I had an error (I don't have the info to share right now).

```
(car/xadd stream-name :MAXLEN 1000 "*" data-map)
```

I think I probably need to do something like this instead, so will give this a try.

 ```
(car/xadd stream-name "MAXLEN" "~" 1000 "*" data-map)
```

Thanks
