### ISSUE TITLE
MessageQueue max queue size

### ISSUE THREAD

**Issue by marioaquino** [ptaoussanis/carmine#265]
I notice that the message queue monitor-fn [expresses a default max-queue size of 1000](https://github.com/ptaoussanis/carmine/blob/master/src/taoensso/carmine/message_queue.clj#L349).  Is this number arbitrary?  If not, what defines that constraint?

**Comment by ptaoussanis** [comment]
Hi Mario! This is an arbitrary number, you can replace it with whatever you like 👍

**Comment by marioaquino** [comment]
That helps.  Thanks, @ptaoussanis!
