### ISSUE TITLE
Carmine message queue v2

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/carmine#278]

**Comment by devurandom** [comment]
Do you have an ETA for Carmine v3.3, i.e. when this feature will be released?

**Comment by ptaoussanis** [comment]
@devurandom Hi Dennis,

Was actually planning to have it out already last week - but got sidetracked by some other open-source work.

Should be ready within the next 1-2 weeks (so ~mid July).

I'm curious - is there some particular reason you're waiting on this?

**Comment by devurandom** [comment]
Thanks!

> is there some particular reason you're waiting on this?

Yes. As I understood from https://github.com/ptaoussanis/carmine/issues/223, this will bring per-task timeouts, which has proven to be necessary for our system.

**Comment by ptaoussanis** [comment]
> Yes. As I understood from https://github.com/ptaoussanis/carmine/issues/223, this will bring per-task timeouts

Correct, that will be included 👍 Sorry about the delays!
Will try get a pre-release out by the end of this week.

**Comment by ptaoussanis** [comment]
Closing, will be addressed in forthcoming release.
Should be up tomorrow, working on final testing and release notes now.

Thanks again for all the patience on this!

**Comment by ptaoussanis** [comment]
v3.3.0-RC1 is now on Clojars, release notes [here](https://github.com/ptaoussanis/carmine/releases/tag/v3.3.0-RC1).

Given the amount of code touched, please tread carefully and confirm everything's working as expected before putting into production 🙏
