### ISSUE TITLE
HGETALL not returning a hashmap

### ISSUE THREAD

**Issue by honza** [ptaoussanis/carmine#4]
Using `[carmine "0.8.2-SNAPSHOT"]`

``` clojure
(ns cartest.core
    (:require
     [carmine (core :as r)] 
      ))

(def pool (r/make-conn-pool :test-while-idle? true))
(def spec-server1 (r/make-conn-spec :host     "127.0.0.1"
                                    :db 0
                                    :port     6379))
(defmacro redis
    "Basically like (partial with-conn pool spec-server1)."
      [& body] `(r/with-conn pool spec-server1 ~@body))

(defn -main
  [& args]
  (println
    (redis
        (r/hgetall "hit:1"))

    ))

;; (url /admin/ added 20120606 user honza datetime 2012-06-06 00:42:30)
;;
;; Expected:
;; {:url /admin/ :added 20120606 :user honza :datetime <date time inst>}
;;
;; redis-cli:
;; hgetall hit:1
;; 1) "url"
;; 2) "/admin/"
;; 3) "added"
;; 4) "20120606"
;; 5) etc...
```

Disclaimer: I'm a Clojure n00b and there might be something obviously wrong with my code. I apologize in advance.

**Comment by jiacai2050** [comment]
This issus is still exits in `2.15.1`
```
                 [com.taoensso/carmine "2.15.1"]
```

**Comment by ptaoussanis** [comment]
> This issus still exits in 2.15.1, Anybody look into this ?

@jiacai2050 Hi there! Sorry, can you be a little more specific- what issue are you experiencing?

**Comment by jiacai2050** [comment]
@ptaoussanis I just want `hgetall` return a map, and find `(car/hgetall* key keywordize?)` does the job.

**Comment by ptaoussanis** [comment]
Ahh, gotcha :-)

**Comment by theronic** [comment]
Newest docs show hgetall* is deprecated and should use "parse-map", but it doesn't keywordize keys. Is there a flag I'm missing?

**Comment by piero** [comment]
For the benefit of those who'll be looking for an answer to the previous question, "parse-map" takes the `:keywordize` argument, in example:

```
(car/hset "my-key" :answer 42)
=> 1

(car/hgetall "my-key")
=> ["answer" "42"]

(car/parse-map (car/hgetall "my-key") :keywordize)
=> {:answer "42"}
```
